test push images

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -16,6 +16,15 @@ stages:
       pool:
         vmImage: 'Ubuntu-16.04'
       steps:
+
+      - task: HelmInstaller@1
+        displayName: Helm installer
+        inputs:
+          helmVersionToInstall: 2.15.1
+
+      - script: helm lint $(System.DefaultWorkingDirectory)/helm/simple-pipeline/
+        displayName: Helm Lint
+
       - task: Docker@2
         displayName: Build server
         inputs:
@@ -35,6 +44,59 @@ stages:
           docker push $(serverImageName):latest
           docker push $(appImageName):latest
         displayName: Docker push
-        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+        # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+      
+      # Copies Helm chart to $(Build.ArtifactStagingDirectory)
+      - task: HelmDeploy@0
+        inputs:
+          command: 'package'
+          chartPath: '$(System.DefaultWorkingDirectory)/helm/simple-pipeline'
+          chartVersion: '1.0.0'
+        displayName: Package Helm Chart
+      
+      - task: PublishPipelineArtifact@1
+        inputs:
+          targetPath: '$(Build.ArtifactStagingDirectory)'
+          artifact: 'artifacts'
+        displayName: Publish Pipeline Artifacts in $(Build.ArtifactStagingDirectory)
+
+  - stage: Deploy
+    dependsOn: CI
+#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
+    jobs:
+    - deployment: Deploy
+      pool:
+        vmImage: 'Ubuntu-16.04'
+      environment: 'nonprod'
+      strategy:
+        runOnce:
+          deploy:
+            steps:
+
+            - task: HelmInstaller@1
+              displayName: Helm installer
+              inputs:
+                helmVersionToInstall: 2.15.1
+            
+            - script: |
+                set -euo pipefail
+                
+                if [[ ! -e $(find $AGENT_BUILDDIRECTORY/artifacts/simple-pipeline-*.tgz) ]]; then
+                    echo "Could not find Helm chart artifact at directory: $AGENT_BUILDDIRECTORY/artifacts/"
+                    exit 1
+                fi
+                echo "##vso[task.setvariable variable=HELM_CHART_PACKAGE]$(find $AGENT_BUILDDIRECTORY/artifacts/simple-pipeline-*.tgz)"
+              displayName: Get full path to Helm Chart artifact
+
+            # - task: HelmDeploy@0
+            #   inputs:
+            #     connectionType: 'Kubernetes Service Connection'
+            #     kubernetesServiceConnection: ''
+            #     namespace: 'simple-pipeline'
+            #     command: 'install'
+            #     chartType: 'FilePath'
+            #     chartPath: '$(HELM_CHART_PACKAGE)'
+            #     releaseName: 'simple-pipeline'
+            #   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
             
       
